/****** Object:  Table [dbo].[хТопливо]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[хТопливо](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Код] [int] NULL,
	[SYS_ID] [varchar](32) NOT NULL CONSTRAINT [DF_хТопливо_SYS_ID]  DEFAULT (replace(newid(),'-','')),
	[SYS_T] [int] NULL,
	[SYS_U] [smallint] NULL,
	[SYS_S] [smallint] NULL,
	[SYS_D] [varchar](255) NULL,
	[Состояние] [varchar](255) NULL,
	[Создал] [varchar](255) NULL,
	[Создан] [datetime] NULL,
	[Изменил] [varchar](255) NULL,
	[Изменен] [datetime] NULL,
	[Примечания] [varchar](max) NULL,
	[Проект] [varchar](32) NULL,
	[Тип] [varchar](32) NULL,
	[Номер] [varchar](32) NULL,
	[Дата] [datetime] NULL,
	[Что] [varchar](32) NULL,
	[Откуда] [varchar](32) NULL,
	[ОткудаКА] [varchar](32) NULL,
	[ОткудаМОЛ] [varchar](32) NULL,
	[Куда] [varchar](32) NULL,
	[КудаКА] [varchar](32) NULL,
	[КудаМОЛ] [varchar](32) NULL,
	[Температура] [money] NULL,
	[Плотность] [money] NULL,
	[КоличествоКГ] [decimal](18, 3) NULL,
	[КоличествоЛ] [decimal](18, 3) NULL,
	[ПоСчетчику] [varchar](32) NULL,
	[ПутевойЛист] [varchar](32) NULL,
	[ТТН_Водитель] [varchar](255) NULL,
	[ТТН_ДоверенностьНомер] [varchar](255) NULL,
	[ТТН_ДоверенностьДата] [datetime] NULL,
	[ТТН_ДоверенностьВыдана] [varchar](255) NULL,
	[ТТН_МаркаАвтомобиля] [varchar](255) NULL,
	[ТТН_ГосНомерАвтомобиля] [varchar](255) NULL,
	[ТТН_ВодительУдостоверение] [varchar](255) NULL,
	[ТТН_МаркаПрицепа] [varchar](255) NULL,
	[ТТН_ГосНомерПрицепа] [varchar](255) NULL,
	[ТТН_ПЛНомер] [varchar](255) NULL,
	[ТТН_Заказчик] [varchar](255) NULL,
	[ТТН_Перевозчик] [varchar](255) NULL,
	[ТТН_ПунктПогрузки] [varchar](255) NULL,
	[ТТН_ПунктРазгрузки] [varchar](255) NULL,
	[ТТН_ВидПеревозки] [varchar](255) NULL,
	[ТТН_ЛицензионнаяКарточка] [varchar](255) NULL,
	[ТТН_СрокДоставки] [datetime] NULL,
	[ТТН_Плательщик] [varchar](255) NULL,
	[М7_МестоСоставления] [varchar](255) NULL,
	[М7_ВремяНачало] [varchar](255) NULL,
	[М7_ВремяКонец] [varchar](255) NULL,
	[М7_ПринятОсмотрен] [varchar](255) NULL,
	[М7_УдостКачества] [varchar](255) NULL,
	[М7_СоСтанцииПристани] [varchar](255) NULL,
	[М7_Отправитель] [varchar](255) NULL,
	[М7_Поставщик] [varchar](255) NULL,
	[М7_Получатель] [varchar](255) NULL,
	[М7_Страховщик] [varchar](255) NULL,
	[М7_ДатаОтправки] [datetime] NULL,
	[М7_Телефонограмма] [varchar](255) NULL,
	[М7_УсловияХранения] [varchar](255) NULL,
	[М7_СостояниеТарыУпаковки] [varchar](255) NULL,
	[М7_КолвоНедостПрод] [varchar](255) NULL,
	[М7_ДругиеДанные] [varchar](255) NULL,
	[М7_ЗаключениеКомиссии] [varchar](255) NULL,
	[М7_Приложение] [varchar](255) NULL,
	[М7_ДВ_ПрибытиеНаСтанцию] [datetime] NULL,
	[М7_ДВ_ВыдачаГруза] [datetime] NULL,
	[М7_ДВ_ВскрытияВагона] [datetime] NULL,
	[М7_ДВ_ДОставкаНаСклад] [datetime] NULL,
	[М7_ПоТСДНомер] [varchar](255) NULL,
	[М7_ПоТСДДата] [datetime] NULL,
	[М7_ПоТСДВагоны] [varchar](255) NULL,
	[М7_ДоговорПоставкиДата] [datetime] NULL,
	[М7_ДоговорПоставкиНомер] [varchar](255) NULL,
	[М15_Основание] [varchar](255) NULL,
	[М15_КомуФио] [varchar](255) NULL,
	[М15_КомуДолжность] [varchar](255) NULL,
 CONSTRAINT [PK_хТопливо] PRIMARY KEY CLUSTERED 
(
	[SYS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

